//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_Contractor
    {
        public int Contractor_Id { get; set; }
        public string PAN { get; set; }
        public string TIN { get; set; }
        public byte Ref_Role_Id { get; set; }
        public string Contractor_Name { get; set; }
        public string Contractor_Password { get; set; }
        public string Contractor_Bldg { get; set; }
        public string Contractor_Street { get; set; }
        public string Contractor_Area { get; set; }
        public int Contractor_Zipcode { get; set; }
        public string Contractor_CIty { get; set; }
        public byte Contractor_State_Id { get; set; }
        public byte Contractor_Country_Id { get; set; }
        public long Contractor_Mobile { get; set; }
        public bool Contractor_Mobile_Verification { get; set; }
        public string Contractor_Email { get; set; }
        public bool Contractor_Email_Verification { get; set; }
        public bool Contractor_Active { get; set; }
        public byte Contractor_Created_By { get; set; }
        public System.DateTime Contractor_Created_Date { get; set; }
        public string EPROC_No { get; set; }
        public string Mobile_OTP { get; set; }
        public bool Tally_Status { get; set; }
    }
}
